# Generated by Django 5.0.6 on 2024-05-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.ManyToManyField(to='shop.quality'),
        ),
    ]
